### ISSUE TITLE
Investigate methods to avoid broken articles

### ISSUE THREAD

**Issue by marceljar** [SenecaCollegeBTSProjects/Group_07#10]
- Right now, some articles will not show up in your system
- Check if there is a way to detect such articles, and provide the user with a link of this article, instead of a broken page

**Comment by GeoffMcCollam** [comment]
Articles not appearing due to the xframes being set to 'deny' or 'sameorigin' in the headers will now appear as a link to the article instead of a broken page.

**Comment by marceljar** [comment]
Make sure to let the user know that the article cannot be fetched, prior to giving him/her the link to follow it.
