### ISSUE TITLE
Add Comments

### ISSUE THREAD

**Issue by marceljar** [SenecaCollegeBTSProjects/Group_07#11]
- Allow users to add comments to articles
- Users can also edit and/or delete comments
- The system show show a timestamp for the comment (if a comment was edited, the timestamp will be for the edit)
- When an article with comments is accessed, users will be able to see the comments that were already made

**Comment by pavelsinelnikov** [comment]
cb3207b394a86ab32ba245ae491de447aa8ea358
Done!

**Comment by marceljar** [comment]
The back-end seems to be perfect. The front-end still needs some polishing. -2 marks
