### ISSUE TITLE
Changes to the type of data to be fetched

### ISSUE THREAD

**Issue by marceljar** [SenecaCollegeBTSProjects/Group_07#12]
- Investigate the possibility of fetching news ABOUT countries, instead of FROM countries
- Investigate the possibility of selecting more than one country

**Comment by drew5494** [comment]
9df81e82

**Comment by marceljar** [comment]
First part done. To present the second part during our next meeting.

**Comment by marceljar** [comment]
Done, but not perfect. 20/25
